// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEDfswSnZjLoc6EXz9GEaprK-IRsjHS3k',
    appId: '1:577966694504:web:placeholder',
    messagingSenderId: '577966694504',
    projectId: 'my-bmta-project',
    authDomain: 'my-bmta-project.firebaseapp.com',
    storageBucket: 'my-bmta-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEDfswSnZjLoc6EXz9GEaprK-IRsjHS3k',
    appId: '1:577966694504:android:47c4e241ce19574fe3dbdd',
    messagingSenderId: '577966694504',
    projectId: 'my-bmta-project',
    storageBucket: 'my-bmta-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3mvSg2-gUBOFxlWEfs0CfqtOtinqSBoo',
    appId: '1:577966694504:ios:db4a7bcf0f6cadfde3dbdd',
    messagingSenderId: '577966694504',
    projectId: 'my-bmta-project',
    storageBucket: 'my-bmta-project.firebasestorage.app',
    iosBundleId: 'com.example.bmtaApp',
  );
}
